# Generated by Django 4.2.1 on 2023-06-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhistory', '0005_rename_prediction_value_text_isfakenews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='text',
            name='user',
        ),
    ]
