version: "3.8"
services:
  postgres:
    build: ./database
    environment: 
      - POSTGRES_PASSWORD=example
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend_network
  frontend:
    build: ./frontend
    volumes: 
      - ./frontend:/app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    build: ./proxy
    ports:
      - 80:80
    links:
      - authentication_service
    depends_on:
      - authentication_service
    networks:
      - backend_network
  authentication_service:
    restart: always
    build: ./authentication_service
    volumes: 
      - ./authentication_service:/app
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend_network
  predict_service:
    restart: always
    build: ./predict_service
    volumes: 
      - ./predict_service:/app
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend_network
  history_service:
    restart: always
    build: ./history_service
    volumes: 
      - ./history_service:/app
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend_network
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network: