version: "3.8"
services:
  postgres:
    build: ./database
    environment: 
      - POSTGRES_PASSWORD=example
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend_network
  predict:
    build: ./predict
    env_file: ./predict/.env
    volumes: 
      - ./predict:/app
    depends_on:
      - postgres
    expose: 
      - "9000"
    networks:
      - backend_network
  history:
    build: ./history
    env_file: ./history/.env
    volumes:
      - ./history:/app
    depends_on:
      - postgres
    expose:
      - "9001"
    networks:
      - backend_network
  userapi:
    build: ./userapi
    env_file: ./userapi/.env
    volumes:
      - ./userapi:/app
    depends_on:
      - postgres
    expose:
      - "9002"
    networks:
      - backend_network
  frontend:
    build: ./frontend
    volumes: 
      - ./frontend:/app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    build: ./proxy
    ports:
      - 80:80
    links:
      - predict
      - history
      - userapi
    depends_on:
      - predict
      - history
      - userapi
    networks:
      - backend_network
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 15672:15672
      - 5672:567
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network: