version: "3.8"
services:
  postgres:
    build: ./database
    environment: 
      - POSTGRES_PASSWORD=example
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes: 
      - ./backend:/app
    depends_on:
      - postgres
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build: ./frontend
    volumes: 
      - ./frontend:/app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db_data: