# Generated by Django 4.2.1 on 2023-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsdetectorcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistoryentry',
            name='is_fake_news',
            field=models.BooleanField(default=False),
        ),
    ]
