# Generated by Django 4.2.1 on 2023-06-11 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userhistory', '0002_text_delete_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='is_fake_news',
            field=models.BooleanField(default=False),
        ),
    ]
