name: Docker Image CI to Azure CR

on:
  push:
    tags:
      - '*'

jobs:
   build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_REGISTRY_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          
    - name: Extract Tag Name
      id: get_tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push PostgreSQL
      uses: docker/build-push-action@v2
      with:
        context: ./database
        file: ./database/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/postgres:${{ env.RELEASE_TAG }}
        build-args:
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

     # Code Inspector Analysis
    - name: Run Code Inspector Analysis
      uses: codeinspectorio/github-action@master
      with:
        token: ${{ secrets.CODE_INSPECTOR_TOKEN }}
        project_name: "<Your_Code_Inspector_Project_Name>"
        # Optional: fail the job on low score
        threshold: 80

    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/frontend:${{ env.RELEASE_TAG }}

    - name: Build and push Nginx
      uses: docker/build-push-action@v2
      with:
        context: ./proxy
        file: ./proxy/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/nginx:${{ env.RELEASE_TAG }}

    - name: Build and push Authentication Service
      uses: docker/build-push-action@v2
      with:
        context: ./authentication_service
        file: ./authentication_service/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/authentication_service:${{ env.RELEASE_TAG }}

    - name: Build and push Predict Service
      uses: docker/build-push-action@v2
      with:
        context: ./predict_service
        file: ./predict_service/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/predict_service:${{ env.RELEASE_TAG }}

    - name: Build and push History Service
      uses: docker/build-push-action@v2
      with:
        context: ./history_service
        file: ./history_service/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/history_service:${{ env.RELEASE_TAG }}

    - name: Build and push ML Service
      uses: docker/build-push-action@v2
      with:
        context: ./ml_service
        file: ./ml_service/Dockerfile
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/ml_service:${{ env.RELEASE_TAG }}
